apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: postgres-exporter
  namespace: monitoring
spec:
  namespaceSelector:
    matchNames:
      - monitoring
  selector:
    matchLabels:
      monitoring: postgres-exporter
  endpoints:
    - port: http
      path: /metrics
      interval: 10s
      scrapeTimeout: 5s
      scheme: http
