apiVersion: v1
kind: Secret
metadata:
  name: postgres-exporter-dsn
  namespace: monitoring
type: Opaque
stringData:
  DATABASE_URL: postgresql://postgres_exporter:REPLACE_ME@postgres.url-shortener.svc.cluster.local:5432/url_shortener?sslmode=disable
