apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: url-shortener-db-external-secret
  namespace: url-shortener
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: url-shortener-secretstore
    kind: SecretStore
  target:
    name: url-shortener-secrets
    creationPolicy: Owner
  data:
    - secretKey: DATABASE_URL
      remoteRef:
        # OCI Secrets Manager secret OCID
        key: "ocid1.vaultsecret.oc1.phx.amaaaaaar32he3qa7gnaib22v56ndj6dlxllgwitywthz6jl3rgwfjyzw72a"
        # optional: use specific version number; omit to use latest
        version: "1"
