apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: url-shortener-db-external-secret
  namespace: url-shortener
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: url-shortener-secretstore
    kind: SecretStore
  target:
    name: url-shortener-secrets
    creationPolicy: Owner
  data:
    - secretKey: DATABASE_URL
      remoteRef:
        # OCI Secrets Manager secret OCID
        key: "url-shortener-db-url"
        # optional: use specific version number; omit to use latest
    - secretKey: LOADTEST_BYPASS_KEY
      remoteRef:
        key: "url-shortener-loadtest-bypass-key"
