controller:
  service:
    # 핵심: 로드 밸런서 타입을 'nlb'로 지정
    annotations:
      oci.oraclecloud.com/load-balancer-type: "nlb"
      
      # NLB는 Flexible Shape 설정(Mbps)이 필요 없습니다. (지워도 됨)
      # traffic policy는 Local을 권장 (클라이언트 IP 보존)
    externalTrafficPolicy: Local
    
    # NLB는 L4이므로 http/https 포트를 그대로 열어줍니다.
    ports:
      http: 80
      https: 443
  
