apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- namespace.yaml
- configmap.yaml
- secretstore.yaml
- externalsecret.yaml
- deployment.yaml
- service.yaml
- issuer.yaml
- ingress.yaml

images:
- digest: sha256:0eacbb9d0340c8402a42a5f87b3fe79116c385fe5b8cb686d6394ea1da6b73ab
  name: phx.ocir.io/ax4dlruayn0q/url-shortener-repository
  newName: phx.ocir.io/ax4dlruayn0q/url-shortener-repository
