apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- configmap.yaml
- secretstore.yaml
- externalsecret.yaml
- deployment.yaml
- service.yaml
- issuer.yaml
- ingress.yaml

images:
- digest: sha256:7711f1569099a5c0fb29e9c58491e36007005432a84c5b6d8dec8e372df5d0d2
  name: phx.ocir.io/ax4dlruayn0q/url-shortener-repository
  newName: phx.ocir.io/ax4dlruayn0q/url-shortener-repository
