apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: url-shortener-spc
  namespace: url-shortener
spec:
  provider: oci
  parameters:
    # Required values — replace placeholders with your OCIDs and region
    secrets: |
      - secretName: "ocid1.vault.oc1.phx.efusu7y5aaap4.abyhqljr76mqeyfvps7yzey2ryzba4ftv7twp5tgtay52y7unjjnff4xkloa"
        secretVersion: "1"
        objectName: "url-shortener-db-url"
    tenancy: ""
    region: "us-phoenix-1"
    # Choose authType that fits your OKE nodes: instance_principal (for OKE on OCI),
    # resource_principal (if using OKE-managed OIDC), or user_principal with configFile profile.
    authType: "instance_principal"
  secretObjects:
    - secretName: url-shortener-secrets
      type: Opaque
      data:
        - key: DATABASE_URL
          objectName: database-url
