apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: url-shortener-secretstore
  namespace: url-shortener
spec:
  provider:
    oracle:
      vault: "ocid1.vault.oc1.phx.efusu7y5aaap4.abyhqljr76mqeyfvps7yzey2ryzba4ftv7twp5tgtay52y7unjjnff4xkloa"
      region: "us-phoenix-1"
      auth:
        instancePrincipal: {}