apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: urlshortner-secrets
  namespace: urlshortner
stringData:
  # Point to your RDS/PostgreSQL instance
  DATABASE_URL: 'postgresql://postgres:3dtx9WDYxkyUgy7WDDP5@HOST:5432/urlshortener'
