apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: urlshortener-secrets
  namespace: urlshortener
stringData:
  # Point to your RDS/PostgreSQL instance
  # DATABASE_URL: 'postgresql://postgres:postgres@db:5432/urlshortener'
  POSTGRES_USER: urlshortener-user
  POSTGRES_PASSWORD: supersecret
  POSTGRES_DB: urlshortener-db
