apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: urlshortener
type: Opaque
stringData:
  POSTGRES_USER: urlshortener-postgres-user
  POSTGRES_PASSWORD: supersecret
  POSTGRES_DB: urlshortener-postgres-db
  DATABASE_URL: postgresql://urlshortener-postgres-user:supersecret@postgres-service:5432/urlshortener-postgres-db
