apiVersion: v1
kind: Service
metadata:
  name: postgres-service
  namespace: urlshortener
  labels:
    app: postgres
spec:
  type: ClusterIP
  selector:
    app: postgres
  ports:
    - name: postgres
      port: 5432        # 서비스 포트
      targetPort: 5432  # 컨테이너 포트
